<?php
/**
*	Archivo de redireccion en paginas
*	//
*/
include_once("core/core.deprecated.inc.php");
include_once("core/core.error.inc.php");
$id = ( isset($_GET["i"]) ) ? $_GET["i"] : DEFAULT_CODIGO_DE_ERROR; 

$xErr	= new cError($id);
$xErr->init();
	
?>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="description" content="" />
<meta name="format-detection" content="telephone=no" />
<meta name="author" content="Luis Humberto Balam Gonzalez" />
<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<?php
echo "<title>" . EACP_NAME . "</title>"; 
?>

<link href="css/inicio.css" rel="stylesheet" type="text/css">
<!--  <link href="css/global.css" rel="stylesheet" type="text/css">-->
</head>

</head>
<style>
h3 {
	padding: 1em;
	font-size:3em;
	color: #555;
	animation: tracking-in-contract-bck-top 1s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
}
.error-num {
	font-size:6em;
	color: #3e3e3e;
	animation: text-pop-up-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}
p {
	padding: 1em;
}
/* ----------------------------------------------
 * Generated by Animista on 2018-7-25 17:16:58
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tracking-in-contract-bck-top
 * ----------------------------------------
 */
@keyframes tracking-in-contract-bck-top {
  0% {
    letter-spacing: 1em;
    transform: translateZ(400px) translateY(-300px);
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    transform: translateZ(0) translateY(0);
    opacity: 1;
  }
}

@keyframes text-pop-up-top {
  0% {
    transform: translateY(0);
    transform-origin: 50% 50%;
    text-shadow: none;
  }
  100% {
    transform: translateY(-50px);
    transform-origin: 50% 50%;
    text-shadow: 0 1px 0 #cccccc, 0 2px 0 #cccccc, 0 3px 0 #cccccc, 0 4px 0 #cccccc, 0 5px 0 #cccccc, 0 6px 0 #cccccc, 0 7px 0 #cccccc, 0 8px 0 #cccccc, 0 9px 0 #cccccc, 0 50px 30px rgba(0, 0, 0, 0.3);
  }
}





</style>
<body>
<form id="login">
<?php echo $xErr->getFicha(); ?>
<!--  <span class="container">
	
	<svg class="loader" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 340 340">
		 <circle cx="170" cy="170" r="160" stroke="#E2007C"/>
		 <circle cx="170" cy="170" r="135" stroke="#404041"/>
		 <circle cx="170" cy="170" r="110" stroke="#E2007C"/>
		 <circle cx="170" cy="170" r="85" stroke="#404041"/>
	</svg>
	
</span>-->
</form>
</body>
</html>
